# Generated by Django 6.0.5 on 2026-06-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_incident'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blood_type',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='chronic_diseases',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='emergency_contact',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='other_medical_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.CharField(choices=[('tripoli', 'طرابلس'), ('benghazi', 'بنغازي'), ('misrata', 'مصراتة'), ('zawiya', 'الزاوية'), ('sabha', 'سبها'), ('khums', 'الخمس'), ('zliten', 'زليتن'), ('gharyan', 'غريان'), ('bayda', 'البيضاء'), ('tobruk', 'طبرق'), ('sirte', 'سرت'), ('tarhuna', 'ترهونة'), ('kufra', 'الكفرة'), ('derna', 'درنة')], default='tripoli', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'مستخدم عادي'), ('volunteer', 'متطوع مسعف'), ('government', 'جهة حكومية')], default='user', max_length=20),
        ),
    ]
