# Generated by Django 5.2.13 on 2026-06-09 19:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_incident_voice_note_alter_incident_injury_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='declined_volunteers',
            field=models.ManyToManyField(blank=True, related_name='declined_incidents', to=settings.AUTH_USER_MODEL),
        ),
    ]
