# Generated by Django 5.2.13 on 2026-07-17 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_incident_declined_volunteers'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='gov_responder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gov_assigned_incidents', to=settings.AUTH_USER_MODEL),
        ),
    ]
